language: csharp
solution: LiteNetLib.sln
install:
  - nuget restore LiteNetLib.sln
script:
  - xbuild /p:Configuration=Release /target:"LiteNetLib;LibSample" LiteNetLib.sln 
notifications:
  email: false